DROP DATABASE IF EXISTS rgca_db;
CREATE DATABASE rgca_db;

USE rgca_db;

CREATE TABLE games (
  id INT AUTO_INCREMENT NOT NULL,
  romLink VARCHAR(1000) NOT NULL,
  title VARCHAR(200) NOT NULL,
  rating VARCHAR(10),
  imageLink VARCHAR(1000) NOT NULL,
  
 
  description VARCHAR(1000) NOT NULL,
  PRIMARY KEY(id)
);